[project]
name = "video-jungle-agent-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai-tools>=0.36.0",
    "crewai>=0.102.0",
    "videojungle>=0.1.39",
]
