video_editor_task:
  description: >
    Think through the best way to present on {topic}, according to the script {script}.
    You have access to a video library to create 30-60 second style documentary clips.
    These should be formatted for social media, with a focus on engaging the audience.
    Here are the clips you have access to:
    {video_clips}
  expected_output: >
   {video_format}
  agent: video_editor

sourcing_task:
  description: >
    Create a list of seach terms and sources for {topic}. You should include a variety of sources
    from videos. The goal is to provide a comprehensive set of source videos for an editor to use.
  expected_output: >
    A list of the video ids, along with the timepoints to include with a description of each video.
  agent: video_sourcing_agent

scriptwriting_task:
  description: >
   Write a voiceover script for the video edit on {topic}. The voiceover should be engaging and informative,
    and should be timed to match the video clips. Here is the script you will be reading:
    {script}
  expected_output: >
    A voiceover script that is engaging and informative, and fits into a social media style post.
  agent: voiceover_artist